### ISSUE TITLE
Toggle enhancement

### ISSUE THREAD

**Issue by Ninos** [Wikiki/bulma-accordion#11]
Hey there,
would be awesome to have some functionality for disabling toggle on sibling accordions. So after opening an accordion other accordions stay open. May you could add a class to accordions-element, e.g. is-toggleable

**Comment by repetemusic** [comment]
workaround here ymmv

https://github.com/Wikiki/bulma-accordion/issues/14

**Comment by Wikiki** [comment]
Hi @Ninos ,

Package is abandoned in favor of http://github.com/creativebulma/bulma-collapsible. Please use it instead and open an issue if needed on this repository.
