### ISSUE TITLE
hyperlinks are not working on the accordion-content

### ISSUE THREAD

**Issue by KaotiKcr** [Wikiki/bulma-accordion#12]
Hello @Wikiki , 

Playing around with the bulma-accordion I am using it for a sidebar menu, I noted the hyperlinks are not working due the JS script that handles the toggle action.

I have added a condition to avoid the e.PreventDefault() for hyperlinks as:
```
if (e.target.localName != 'a')
    e.preventDefault();
```
this in the onBulmaAccordionClick event.

You should consider to include it and also any other element where the native default must prevail (or any other improved script).

**Comment by Wikiki** [comment]
Hi @KaotiKcr ,

Package is abandoned in favor of http://github.com/creativebulma/bulma-collapsible. Please use it instead and open an issue if needed on this repository.
