### ISSUE TITLE
Accordion is collapsing when clicking inside accordion-content

### ISSUE THREAD

**Issue by alyrik** [Wikiki/bulma-accordion#13]
It can be seen on [demo page](https://wikiki.github.io/components/accordion/). Accordion is suddenly collapsing when clicking any place inside its content. Though documentation says that only element with `toggle` class is responsible for this action.

**Comment by repetemusic** [comment]
got this to work with following on line 136

      this.items = this.element.querySelectorAll('.accordion-header') || [];

**Comment by repetemusic** [comment]
actually it may have been this

line 179
    value: function value(e) {
      if (e.target.localName !== '.accordion-content')
          e.preventDefault();

**Comment by Wikiki** [comment]
Hi @alyrik ,

Package is abandoned in favor of http://github.com/creativebulma/bulma-collapsible. Please use it instead and open an issue if needed on this repository.
