### ISSUE TITLE
toggle is non deterministic

### ISSUE THREAD

**Issue by repetemusic** [Wikiki/bulma-accordion#14]
on its own the toggle behaviour is really hard for user to know what will happen.

in m case i wanted no "old" accordion item to flip when hitting another one

commenting out line 186 accomplishes this, but would be nice for it to be an option
          //activeItem.classList.remove('is-active');

**Comment by Wikiki** [comment]
Hi @repetemusic ,

Package is abandoned in favor of http://github.com/creativebulma/bulma-collapsible. Please use it instead and open an issue if needed on this repository.
