### ISSUE TITLE
IE / ES6 Symbol

### ISSUE THREAD

**Issue by simonwinter** [Wikiki/bulma-accordion#17]
Hi there,

IE has no support for Symbol, & therefore the code is failing. The current project I'm working on has a requirement that we support IE11.

https://caniuse.com/#search=Symbol
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol

I know IE shouldn't be expected to be supported, but it would be cool if the code could be piped through babel to iron these sorts of things out.

The solution for me was to include the in browser version of babel polyfill:

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.6.15/browser-polyfill.min.js"></script>
```

That's an OK solution, but would prefer if this was bundled as part of the gulp task.

Thanks!

**Comment by Wikiki** [comment]
Hi @simonwinter ,

Package is abandoned in favor of http://github.com/creativebulma/bulma-collapsible. Please use it instead and open an issue if needed on this repository.
