### ISSUE TITLE
Race condition in attach()

### ISSUE THREAD

**Issue by andreasscherman** [Wikiki/bulma-accordion#18]
Hi!

Here's the code for the current implementation for `attach()`: https://github.com/Wikiki/bulma-accordion/blob/master/src/js/index.js#L29.

As you can see, the function has async behaviour from the `setTimeout`. However, it does not provide any form of controlling this async behaviour. The documentation states:

`var accordions = bulmaAccordion.attach(); // accordions now contains an array of all Accordion instances`

This is not necessarily true, as it populates the array after 100ms. If I use the `accordions` variable directly after the attach, the array may or may not be populated, depending on timings.

Suggestion is to use a structure which allows you to control this asynchronous behaviour, such as `Promise` or anything of the like. _Or_, you could always make it synchronous.

**Comment by Wikiki** [comment]
Hi @andreasscherman ,

Package is abandoned in favor of http://github.com/creativebulma/bulma-collapsible. Please use it instead and open an issue if needed on this repository.
