### ISSUE TITLE
Accordian title center is not working with has-text-centered

### ISSUE THREAD

**Issue by dhamukrish** [Wikiki/bulma-accordion#19]
Accordian title center is not working with `has-text-centered`. Could you please help on this and below is the sample code to reproduce.
```
<section class="accordions">
  <article class="accordion">
    <div class="accordion-header toggle has-background-white-bis">
      <p class="title is-5 has-text-centered has-text-link">
        Title
      </p>
    </div>
    <div class="accordion-body">
      <div class="accordion-content">
        Some content
      </div>
    </div>
  </article>
</section>

```

**Comment by Wikiki** [comment]
Hi @dhamukrish 

Package is abandoned in favor of http://github.com/creativebulma/bulma-collapsible. Please use it instead and open an issue if needed on this repository.
