### ISSUE TITLE
Path issue

### ISSUE THREAD

**Issue by shaddu** [Wikiki/bulma-accordion#23]
path mentioned in all your example code is missing one folder for js

`<script type="text/javascript" src="/node_modules/bulma-extensions/bulma-accordion/dist/bulma-accordion.min.js"></script>`

Should be 

`<script type="text/javascript" src="/node_modules/bulma-extensions/bulma-accordion/dist/js/bulma-accordion.min.js"></script>`

**Comment by Wikiki** [comment]
Thanks I'll update it.
