### ISSUE TITLE
Accordion can not be fully closed

### ISSUE THREAD

**Issue by GabMic** [Wikiki/bulma-accordion#3]
The accordion has to be with one level open and has no fully closed mode. For example, like in the photo, the first level is opened and can not be closed until another level in the accordion is opened etc'
The accordion should be able to fully close all levels. 
![default](https://user-images.githubusercontent.com/11059876/33513228-18db7ee4-d747-11e7-9af2-63173c298bd6.JPG)

**Comment by Wikiki** [comment]
Fixed by commit #32041b4

**Comment by GabMic** [comment]
Thank you :)
