### ISSUE TITLE
Accordion not working

### ISSUE THREAD

**Issue by jethro1991** [Wikiki/bulma-accordion#4]
I have attempted to use this accordion in my project but it is not working, the JS doesn't seem to be triggering. I have tried adding the JS code in the header and footer and tried importing the JS through npm using import Accordion from 'bulma-extensions/bulma-accordion/accordion'

With the below HTML:

            <section class="accordions">
                <article class="accordion">
                    <div class="accordion-header">
                    <p>Hello World</p>
                    <button class="toggle" aria-label="toggle"></button>
                    </div>
                    <div class="accordion-content">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Pellentesque risus mi</strong>, tempus quis placerat ut, porta nec nulla. Vestibulum rhoncus ac ex sit amet fringilla. Nullam gravida purus diam, et dictum <a>felis venenatis</a> efficitur. Aenean ac <em>eleifend lacus</em>, in mollis lectus. Donec sodales, arcu et sollicitudin porttitor, tortor urna tempor ligula, id porttitor mi magna a neque. Donec dui urna, vehicula et sem eget, facilisis sodales sem.
                    </div>
                </article>
                <article class="accordion">
                    <div class="accordion-header">
                    <p>Hello World</p>
                    <button class="toggle" aria-label="toggle"></button>
                    </div>
                    <div class="accordion-content">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Pellentesque risus mi</strong>, tempus quis placerat ut, porta nec nulla. Vestibulum rhoncus ac ex sit amet fringilla. Nullam gravida purus diam, et dictum <a>felis venenatis</a> efficitur. Aenean ac <em>eleifend lacus</em>, in mollis lectus. Donec sodales, arcu et sollicitudin porttitor, tortor urna tempor ligula, id porttitor mi magna a neque. Donec dui urna, vehicula et sem eget, facilisis sodales sem.
                    </div>
                </article>
                <article class="accordion">
                    <div class="accordion-header">
                    <p>Hello World</p>
                    <button class="toggle" aria-label="toggle"></button>
                    </div>
                    <div class="accordion-content">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Pellentesque risus mi</strong>, tempus quis placerat ut, porta nec nulla. Vestibulum rhoncus ac ex sit amet fringilla. Nullam gravida purus diam, et dictum <a>felis venenatis</a> efficitur. Aenean ac <em>eleifend lacus</em>, in mollis lectus. Donec sodales, arcu et sollicitudin porttitor, tortor urna tempor ligula, id porttitor mi magna a neque. Donec dui urna, vehicula et sem eget, facilisis sodales sem.
                    </div>
                </article>
            </section>

However nothing is collapsible. 

https://jsfiddle.net/2y17snLe/7/

**UPDATE:**

Had some more luck, it applies is-active correctly with the following code but the content still does not collapse:

https://jsfiddle.net/2y17snLe/12/

**FIXED**

Documentation is incorrect, the correct code needs to be:

            <section class="accordions">
                <article class="accordion is-active">
                    <div class="accordion-header">
                    <p>Hello World</p>
                    <button class="toggle" aria-label="toggle"></button>
                    </div>
                    <div class="accordion-body">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Pellentesque risus mi</strong>, tempus quis placerat ut, porta nec nulla. Vestibulum rhoncus ac ex sit amet fringilla. Nullam gravida purus diam, et dictum <a>felis venenatis</a> efficitur. Aenean ac <em>eleifend lacus</em>, in mollis lectus. Donec sodales, arcu et sollicitudin porttitor, tortor urna tempor ligula, id porttitor mi magna a neque. Donec dui urna, vehicula et sem eget, facilisis sodales sem.</p>   
                    </div>
                </article>
                <article class="accordion">
                    <div class="accordion-header">
                    <p>Hello World</p>
                    <button class="toggle" aria-label="toggle"></button>
                    </div>
                    <div class="accordion-body">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Pellentesque risus mi</strong>, tempus quis placerat ut, porta nec nulla. Vestibulum rhoncus ac ex sit amet fringilla. Nullam gravida purus diam, et dictum <a>felis venenatis</a> efficitur. Aenean ac <em>eleifend lacus</em>, in mollis lectus. Donec sodales, arcu et sollicitudin porttitor, tortor urna tempor ligula, id porttitor mi magna a neque. Donec dui urna, vehicula et sem eget, facilisis sodales sem.</p>   
                    </div>
                </article>
                <article class="accordion">
                    <div class="accordion-header">
                    <p>Hello World</p>
                    <button class="toggle" aria-label="toggle"></button>
                    </div>
                    <div class="accordion-body">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Pellentesque risus mi</strong>, tempus quis placerat ut, porta nec nulla. Vestibulum rhoncus ac ex sit amet fringilla. Nullam gravida purus diam, et dictum <a>felis venenatis</a> efficitur. Aenean ac <em>eleifend lacus</em>, in mollis lectus. Donec sodales, arcu et sollicitudin porttitor, tortor urna tempor ligula, id porttitor mi magna a neque. Donec dui urna, vehicula et sem eget, facilisis sodales sem.</p>   
                    </div>
                </article>
            </section>

Change accordion-content to accordion-body

**Comment by Wikiki** [comment]
Hi @jethro1991,

sorry but the documentation is good.
Please verify you are working with the last version.
